local allowCountdown = true
function onCreate()
  makeLuaSprite('bg','BG01',-1000,-400)
  scaleObject('bg',2,2)
  makeLuaSprite('cutout','boi',-150,75)
  scaleObject('cutout',0.9,0.9)
  makeAnimatedLuaSprite('box','MusicBox',350,200)
  addAnimationByPrefix('box','idle','Music',24,true)
  objectPlayAnimation('box','idle',true)
  makeAnimatedLuaSprite('lights','Light(Add-Blend)',-300,-150)
  addAnimationByPrefix('lights','idle','fezt',24,true)
  objectPlayAnimation('lights','idle',true)
  scaleObject('lights',4,4)
  makeLuaSprite('pillar','pillar',1150,-250)
  setScrollFactor('pillar',1.5,1.5)
  addLuaSprite('bg',false)
  addLuaSprite('box',false)
  addLuaSprite('cutout',false)
  addLuaSprite('lights',true)
  addLuaSprite('pillar',true)
end
function onStepHit()
  if curStep==929 then
  startVideo('bendy/1.5')
  setProperty('inCutscene',false)
  makeLuaSprite('bg','bendy/inky depths',-600,-800)
  scaleObject('bg', 2, 2)
  makeLuaSprite('mid','bendy/MidGround',-600,-800)
  scaleObject('mid', 2, 2)
  makeLuaSprite('fg','bendy/Foreground',-600,-400)
  scaleObject('fg', 2, 2)
  makeLuaSprite('nuts','bendy/NUTS',-600,-550)
  scaleObject('nuts', 4, 4)
  makeLuaSprite('chains','bendy/Chains',-600,-600)
  scaleObject('chains', 4, 4)
  setProperty('pillar.visible',false)
  setProperty('lights.visible',false)
  addLuaSprite('bg',false)
  addLuaSprite('mid',false)
  addLuaSprite('fg',true)
  addLuaSprite('chains',false)
  addLuaSprite('nuts',false)
  end
  end